/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automatmp1;

import java.util.ArrayList;
import java.awt.Color;
import java.awt.Container;
import java.awt.Image;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.ImageIcon;


import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author Belle
 */
public class Frame extends javax.swing.JFrame {
	public Container pane;
	
    Formatter formatter = new Formatter();
    
   
    Planet earth = new Planet();
    Planet mars = new Planet();
    
    DefaultListModel dm = new DefaultListModel();
    DefaultListModel dm1 = new DefaultListModel();
    DefaultListModel dm2 = new DefaultListModel();
    Entity s = new Entity("Scientist", "Earth");
    Entity c = new Entity("Cow", "Earth");
    Entity l = new Entity("Lion", "Earth");
    Entity g = new Entity("Grains", "Earth");
    Entity h1 = new Entity("Human 1", "Earth");
    Entity h2 = new Entity("Human 2", "Earth");
    Entity e = new Entity("Scientist", "Earth");
    int m = 0;
    
    /**
     * Creates new form Frame
     */
    
    public Frame() {
        initComponents();
        
        earth.addOccupant(s.name);
        earth.addOccupant(c.name);
        earth.addOccupant(l.name);
        earth.addOccupant(g.name);
        earth.addOccupant(h1.name);
        earth.addOccupant(h2.name);
        earth.addOccupant(e.name);
        
        jList1.setModel(dm);
        dm.addElement(s.name);
        dm.addElement(c.name);
        dm.addElement(l.name);
        dm.addElement(g.name);
        dm.addElement(h1.name);
        dm.addElement(h2.name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    	setSize(800,700);

        sButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        lButton = new javax.swing.JButton();
        gButton = new javax.swing.JButton();
        h1Button = new javax.swing.JButton();
        h2Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        goButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        clrButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        messageTA = new javax.swing.JTextArea();
        jScrollPaneTA = new javax.swing.JScrollPane(messageTA);
        movesLbl = new javax.swing.JLabel();

       // sButton.setText("Scientist");
        sButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonActionPerformed(evt);
            }
        });

        //cButton.setText("Cow");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        //lButton.setText("Lion");
        lButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lButtonActionPerformed(evt);
            }
        });

        //gButton.setText("Grain");
        gButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gButtonActionPerformed(evt);
            }
        });

        //h1Button.setText("Human 1");
        h1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ButtonActionPerformed(evt);
            }
        });

        //h2Button.setText("Human 2");
        h2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Earth");

        jLabel2.setText("Mars");
        
        movesLbl.setText("Moves: 0");

        jScrollPane3.setViewportView(jList1);

        jScrollPane4.setViewportView(jList2);

        jScrollPane5.setViewportView(jList3);
        
       // goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        clrButton.setText("CLEAR");
        clrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrButtonActionPerformed(evt);
            }
        });
        
        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        

		pane = getContentPane();
		pane.setLayout(null);
		
		
		pane.add(jLabel1);
		jLabel1.setBounds(100, 30, 50, 50);
		
		pane.add(jLabel2);
		jLabel2.setBounds(360, 30, 50, 50);
		
		pane.add(movesLbl);
		movesLbl.setBounds(305, 250, 50, 50);
		
		pane.add(jList1);
		jList1.setBounds(70, 80, 100, 150);
		
		pane.add(jList2);
		jList2.setBounds(200, 80, 100, 150);
  
		pane.add(jList3);
		jList3.setBounds(330, 80, 100, 150);
		
		pane.add(messageTA);
		messageTA.setEditable(false);
		messageTA.setBounds(300, 580, 170, 50);
		
		goButton.setBounds(300, 300, 80, 80);
		ImageIcon goImage = new ImageIcon("C:\\Users\\Lucia Pineda\\workspace\\automat\\AutomatMP1\\src\\images\\go.png");
		Image goImg = goImage.getImage();
		Image newGoImg = goImg.getScaledInstance(goButton.getWidth(), goButton.getHeight(), Image.SCALE_SMOOTH); //this makes the image fit the button
		ImageIcon goImageIcon = new ImageIcon(newGoImg);
		goButton.setIcon(goImageIcon);
		pane.add(goButton);
		validate();

		goButton.setOpaque(false);
		goButton.setContentAreaFilled(false);
		goButton.setBorderPainted(false);

		pane.add(clrButton);
		clrButton.setBounds(300, 390, 80, 80);
		
		pane.add(resetButton);
		resetButton.setBounds(300, 480, 80, 80);
		
		sButton.setBounds(70, 270, 80, 80);
		ImageIcon sImage = new ImageIcon("C:\\Users\\Lucia Pineda\\workspace\\AUTOMAT-MP-Pineda-Sayson\\src\\images\\scientist.png");
		Image sImg = sImage.getImage();
		Image newSImg = sImg.getScaledInstance(sButton.getWidth(), sButton.getHeight(), Image.SCALE_SMOOTH); //this makes the image fit the button
		ImageIcon sImageIcon = new ImageIcon(newSImg);
		sButton.setIcon(sImageIcon);
		pane.add(sButton);
		validate();
		
		cButton.setBounds(70, 360, 80, 80);
		ImageIcon cImage = new ImageIcon("C:\\Users\\Lucia Pineda\\workspace\\AUTOMAT-MP-Pineda-Sayson\\src\\images\\Cow.png");
		Image cImg = cImage.getImage();
		Image newCImg = cImg.getScaledInstance(cButton.getWidth(), cButton.getHeight(), Image.SCALE_SMOOTH); //this makes the image fit the button
		ImageIcon cImageIcon = new ImageIcon(newCImg);
		cButton.setIcon(cImageIcon);
		pane.add(cButton);
		validate();
		
		lButton.setBounds(70, 450, 80, 80);
		ImageIcon lImage = new ImageIcon("C:\\Users\\Lucia Pineda\\workspace\\AUTOMAT-MP-Pineda-Sayson\\src\\images\\Lion.png");
		Image lImg = lImage.getImage();
		Image newLImg = lImg.getScaledInstance(lButton.getWidth(), lButton.getHeight(), Image.SCALE_SMOOTH); //this makes the image fit the button
		ImageIcon lImageIcon = new ImageIcon(newLImg);
		lButton.setIcon(lImageIcon);
		pane.add(lButton);
		validate();
		
		gButton.setBounds(170, 270, 80, 80);
		ImageIcon gImage = new ImageIcon("C:\\Users\\Lucia Pineda\\workspace\\AUTOMAT-MP-Pineda-Sayson\\src\\images\\Grains.png");
		Image gImg = gImage.getImage();
		Image newGImg = gImg.getScaledInstance(gButton.getWidth(), gButton.getHeight(), Image.SCALE_SMOOTH); //this makes the image fit the button
		ImageIcon gImageIcon = new ImageIcon(newGImg);
		gButton.setIcon(gImageIcon);
		pane.add(gButton);
		validate();
		
		h1Button.setBounds(170, 360, 80, 80);
		ImageIcon h1Image = new ImageIcon("C:\\Users\\Lucia Pineda\\workspace\\AUTOMAT-MP-Pineda-Sayson\\src\\images\\Human1.png");
		Image h1Img = h1Image.getImage();
		Image newH1Img = h1Img.getScaledInstance(h1Button.getWidth(), h1Button.getHeight(), Image.SCALE_SMOOTH); //this makes the image fit the button
		ImageIcon h1ImageIcon = new ImageIcon(newH1Img);
		h1Button.setIcon(h1ImageIcon);
		pane.add(h1Button);
		validate();

		
		h2Button.setBounds(170, 450, 80, 80);
		ImageIcon h2Image = new ImageIcon("C:\\Users\\Lucia Pineda\\workspace\\AUTOMAT-MP-Pineda-Sayson\\src\\images\\Human2.png");
		Image h2Img = h2Image.getImage();
		Image newH2Img = h2Img.getScaledInstance(h2Button.getWidth(), h2Button.getHeight(), Image.SCALE_SMOOTH); //this makes the image fit the button
		ImageIcon h2ImageIcon = new ImageIcon(newH2Img);
		h2Button.setIcon(h2ImageIcon);
		pane.add(h2Button);
		validate();
		
		

    }// </editor-fold>//GEN-END:initComponents

    private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonActionPerformed
        // TODO add your handling code here:
    //    formatter.appendToPane(jTextPane1, e.name, Color.blue);
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        if(dm1.size() < 3){
            dm1.addElement(s.name);
        }

        if(dm1.size() == 3)
        {
            h2Button.setEnabled(false);
            cButton.setEnabled(false);
            lButton.setEnabled(false);
            gButton.setEnabled(false);
            h1Button.setEnabled(false);
        }
        
        sButton.setEnabled(false);
    }//GEN-LAST:event_sButtonActionPerformed

    private void lButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lButtonActionPerformed
        // TODO add your handling code here:
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        if(dm1.size() < 3){
            dm1.addElement(l.name);
        }
        
        if(dm1.size() == 3)
        {
            sButton.setEnabled(false);
            cButton.setEnabled(false);
            h2Button.setEnabled(false);
            gButton.setEnabled(false);
            h1Button.setEnabled(false);
        }
        
        
        lButton.setEnabled(false);
    }//GEN-LAST:event_lButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        // TODO add your handling code here:
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        if(dm1.size() < 3){
            dm1.addElement(c.name);
        }
        
        if(dm1.size() == 3)
        {
            sButton.setEnabled(false);
            h2Button.setEnabled(false);
            lButton.setEnabled(false);
            gButton.setEnabled(false);
            h1Button.setEnabled(false);
        }
        
        
        cButton.setEnabled(false);
    }//GEN-LAST:event_cButtonActionPerformed

    private void gButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gButtonActionPerformed
        // TODO add your handling code here:
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        if(dm1.size() < 3){
            dm1.addElement(g.name);
        }

        if(dm1.size() == 3)
        {
            sButton.setEnabled(false);
            cButton.setEnabled(false);
            lButton.setEnabled(false);
            h1Button.setEnabled(false);
            h2Button.setEnabled(false);
        }
        
        gButton.setEnabled(false);
    }//GEN-LAST:event_gButtonActionPerformed

    private void h1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ButtonActionPerformed
        // TODO add your handling code here:
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        if(dm1.size() < 3){
            dm1.addElement(h1.name);
        }
        
        if(dm1.size() == 3)
        {
            sButton.setEnabled(false);
            cButton.setEnabled(false);
            lButton.setEnabled(false);
            gButton.setEnabled(false);
            h2Button.setEnabled(false);
        }
        
        
        h1Button.setEnabled(false);
    }//GEN-LAST:event_h1ButtonActionPerformed

    private void h2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ButtonActionPerformed
        // TODO add your handling code here:
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        if(dm1.size() < 3){
            dm1.addElement(h2.name);
        }
        
        
        if(dm1.size() == 3)
        {
            sButton.setEnabled(false);
            cButton.setEnabled(false);
            lButton.setEnabled(false);
            gButton.setEnabled(false);
            h1Button.setEnabled(false);
        }
        
        h2Button.setEnabled(false);
    }//GEN-LAST:event_h2ButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        
        int g = 0;
        String message = new String();
        
        for(int i = 0; i < dm1.size(); i++){
            if(dm1.get(i).equals("Scientist")){
                g = 1;
            }
        }
        System.out.println("g = " + g);

        if(g == 1){ //only if the scientist exists 	
            if(m % 2 == 0){  //if coming from earth to mars
                
                for(int j = 0; j < dm1.size(); j++){ //removes from earth(dm)
             	   System.out.println("Middle[" + j + "] = " + dm1.get(j));
             	   
             	   for(int i = 0; i < dm.size(); i++) {
 	            	   if(dm.get(i).equals(dm1.get(j)))
 	            	   {
 	            		   earth.removeOccupant(dm1.get(j).toString());
 	            		   dm.removeElement(dm1.get(j));
 	            	   }
             	   }       
                 }

                for(int i = 0; i < dm1.size(); i++){ //adds to dm2(mars)
                    dm2.addElement(dm1.get(i));
                    mars.addOccupant(dm1.get(i).toString());
                }
                for(int i = 0; i < 3; i++){ //removes from middle(dm1)
                    if(dm1.size() > 0){
                        dm1.removeElement(dm1.get(0));
                    }
                }
                m = m + 1;
                movesLbl.setText("Moves: " + m);
                
                System.out.println("*****************Number of occupants on earth: " + earth.getOccupants().size());
            }
            
            else{ //if coming from mars to earth  
               System.out.println("SIZEE: " + dm1.size());
               for(int j = 0; j < dm1.size(); j++){ //removes from mars(dm2)
            	   System.out.println("Middle[" + j + "] = " + dm1.get(j));
            	   
            	   for(int i = 0; i < dm2.size(); i++) {
	            	   if(dm2.get(i).equals(dm1.get(j)))
	            	   {
	            		   mars.removeOccupant(dm1.get(j).toString());
	            		   dm2.removeElement(dm1.get(j));
	            	   }
            	   }       
                }
               
               for(int i = 0; i < dm1.size(); i++){ //adds to earth(dm)
                    dm.addElement(dm1.get(i));
                    earth.addOccupant(dm1.get(i).toString());
                }
               
               for(int i = 0; i < 3; i++){  //removes from middle(dm1)
                   if(dm1.size() > 0){
                        dm1.removeElement(dm1.get(0));
                   }
                }
               
               m = m + 1;
               movesLbl.setText("Moves: " + m);
            }
            
            //print current occupants of each planet
        	System.out.println("EARTH'S OCCUPANTS: ");
        	for(int i = 0; i < earth.getOccupants().size(); i++)
        	{
        		System.out.println(earth.getOccupants().get(i));
        	}
        	
        	System.out.println();
        	System.out.println("MARS' OCCUPANTS: ");
        	for(int i = 0; i < mars.getOccupants().size(); i++)
        	{
        		System.out.println(mars.getOccupants().get(i));
        	}
            
            //check if anyone was eaten
            if(earth.check().equals("valid") && mars.check().equals("valid"))
            {
            	System.out.println("Everyone is still OK.");
            	message = "Everyone is still OK.";
            	messageTA.setText(message);
            }
            else {
            	System.out.println("Someone was eaten :(");  
            	
            	if(!(earth.check().equals("valid")))
            	{
            		message = earth.check();
            		messageTA.setText(message);
            	}
            	else if(!(mars.check().equals("valid")))
	            	{
	            		message = mars.check();
	            		messageTA.setText(message);
	            	}
            }
        }
        else {
        	System.out.println("The scientist must be present to travel!");
    		message = "The scientist must be \npresent to travel!";
    		messageTA.setText(message);
        }
        
        if(earth.getOccupants().isEmpty())
        {
        	messageTA.setText("CONGRATS! Everyone made\n it to Mars safely :)");
        }
        
        sButton.setEnabled(true);
        cButton.setEnabled(true);
        lButton.setEnabled(true);
        gButton.setEnabled(true);
        h1Button.setEnabled(true);
        h2Button.setEnabled(true);
    }//GEN-LAST:event_goButtonActionPerformed

    private void clrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrButtonActionPerformed
        // TODO add your handling code here:
        dm1.removeAllElements();
        
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        sButton.setEnabled(true);
        cButton.setEnabled(true);
        lButton.setEnabled(true);
        gButton.setEnabled(true);
        h1Button.setEnabled(true);
        h2Button.setEnabled(true);
        
    }//GEN-LAST:event_clrButtonActionPerformed

    //reset moves to 0, clear all JLists, move everything back to earth
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	m = 0;
    	movesLbl.setText("Moves: " + m);
        
        earth.addOccupant(s.name);
        earth.addOccupant(c.name);
        earth.addOccupant(l.name);
        earth.addOccupant(g.name);
        earth.addOccupant(h1.name);
        earth.addOccupant(h2.name);
        earth.addOccupant(e.name);
        
        mars.removeAllOccupants();
        
    	dm.removeAllElements();
    	dm1.removeAllElements();
    	dm2.removeAllElements();
        
        dm.addElement(s.name);
        dm.addElement(c.name);
        dm.addElement(l.name);
        dm.addElement(g.name);
        dm.addElement(h1.name);
        dm.addElement(h2.name);
        
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        messageTA.setText("");
    	
    }
    
    public boolean decider(Entity e1, Entity e2, Entity e3){
        if(e1.name.equalsIgnoreCase("Lion")){
            
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cButton;
    private javax.swing.JButton clrButton;
    private javax.swing.JButton gButton;
    private javax.swing.JButton goButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton h1Button;
    private javax.swing.JButton h2Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton lButton;
    private javax.swing.JButton sButton;
    private javax.swing.JTextArea messageTA;
    private javax.swing.JLabel movesLbl;
    private javax.swing.JScrollPane jScrollPaneTA;
    // End of variables declaration//GEN-END:variables
}
